# Data source definition
data_source:
  parameters:
    db:
      id: "48552c65-8c07-44b6-aa5c-74ef2fce002f"
      region: "us-east1"
      keyspace: "public"
    application:
      token: "AstraCS:RawszStYieKGNvPbZbylktYX:d4250b373716022a09e8cf549d10e1c788df80d29bcead5ef1fe4a6a3d50f5c2"
    
# Parameters for anomaly detection
anomaly_detection:
  significance_level: 
    minimum: 0.01
    maximum: 0.1
    default: 0.05
    step: 0.01
    
# Map configuration
basemap:
  url: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
  attribution: "NearBPO"
  center:
    latitude: -34.6989
    longitude: -64.7597
  zoom: 4
  colors: { 'N': '#e6ab02', 'QC': '#e41a1c', 'V': '#33a02c' }
  legend: { 'N': 'Not checked', 'QC': 'QC failed', 'V': 'QC passed' }